### ISSUE TITLE
 Illegal constant pool index

### ISSUE THREAD

**Issue by message** [cryptoheaven/CryptoHeaven#1]
Hey guys, i don't think it's your code issue, but i get 

```
Exception in thread "main" java.lang.ClassFormatError: Illegal constant pool index 3751 for method signature in class file java/util/regex/Pattern
    at java.lang.ClassLoader.findBootstrapClass(Native Method)
    at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1012)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.install4j.runtime.installer.helper.InstallerUtil.<clinit>(Unknown Source)
    at com.install4j.runtime.launcher.FirstRun.firstRun(Unknown Source)
    at com.install4j.runtime.launcher.FirstRun.checkFirstRun(Unknown Source)
    at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
```

with latest version on Ubuntu. Tried to `rm -rf` and reinstall. Same... Ideas?

**Comment by message** [comment]
Java reinstall helped
